#**LAB : 2**

Ques 1:Suppose you have a dataset containing daily temperature readings for a city, and you want to identify days with extreme temperature conditions. Find days where the temperature either exceeded 35 degrees celcius(not day) or dropped below 5 degrees celcius(cold day).

Input: temperature=np.array([32.5,34.2,36.8,29.3,31.0,38.7,23.1,18.5,22.8,37.2])

Output: Hot Days: Day Temperature(c) 3 : 36.8, 6 : 38.7, 10 : 37.2

Cold days: Day Temperature(C) 11 : 4.0, 14 : -4.0, 15 : -12.0

In [ ]:
import numpy as np
temperature = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2, 4.0, 6.5, 5.5, -4.0, -12.0])
hot_days = []
cold_days = []

for day, temp in enumerate(temperature, start=1):
    if temp > 35:
        hot_days.append((day, temp))
    elif temp < 5:
        cold_days.append((day, temp))

print("Hot Days:")
print("Day      Temperature(C)")
for day, temp in hot_days:
    print(day,"\t",temp)

print("\nCold Days:")
print("Day      Temperature(C)")
for day, temp in cold_days:
     print(day,"\t",temp)

Hot Days:
Day      Temperature(C)
3 	 36.8
6 	 38.7
10 	 37.2

Cold Days:
Day      Temperature(C)
11 	 4.0
14 	 -4.0
15 	 -12.0


Ques:2 Suppose you have a dataset containg months sales data for a company, and you want to split this data into quarterly reports for analysis and reporting purposes.

Input: monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])

Output:

Quarter 1 Sales (in thousands of dollars): [120 135 148]

Quarter 2 Sales (in thousands of dollars): [165 180 155]

Quarter 3 sales (in thousands of dollars):

[168 190 205]

Quarter 4 sales (in thousands of dollars):

[198 210 225]

In [ ]:
import numpy as np
monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])
# Split the data into 4 quarters
quarters = np.split(monthly_sales, 4)

print("Quarter 1 Sales (in thousands of dollars):")
print(quarters[0])

print("\nQuarter 2 Sales (in thousands of dollars):")
print(quarters[1])

print("\nQuarter 3 Sales (in thousands of dollars):")
print(quarters[2])

print("\nQuarter 4 Sales (in thousands of dollars):")
print(quarters[3])


Quarter 1 Sales (in thousands of dollars):
[120 135 148]

Quarter 2 Sales (in thousands of dollars):
[165 180 155]

Quarter 3 Sales (in thousands of dollars):
[168 190 205]

Quarter 4 Sales (in thousands of dollars):
[198 210 225]


Ques:3 Suppose you have a dataset containing customer data, and you want to split this data into two groups: one group for customers who made a purchase in the last 30 days and another group for customers who haven't made a purchase in the last 30 days.

Input:

customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])

Output: Active Customers (Last Purchase<=30 days ago): [101 102 103 104 105]

Inactive Customers (Lasst Purchase> 30 Days ago): [106 107 108 109 110]

In [ ]:
import numpy as np

customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])

active_mask = last_purchase_days_ago <= 30
inactive_mask = last_purchase_days_ago > 30

# Split the customer IDs into active and inactive groups based on the masks
active_customers = customer_ids[active_mask]
inactive_customers = customer_ids[inactive_mask]

print("Active Customers (Last Purchase <= 30 days ago):")
print(active_customers)
print("\nInactive Customers (Last Purchase > 30 days ago):")
print(inactive_customers)

Active Customers (Last Purchase <= 30 days ago):
[101 102 103 104 105]

Inactive Customers (Last Purchase > 30 days ago):
[106 107 108 109 110]


Ques 4: Suppose you have two sets of employee data—one containing information about full-time employees and another containing information about part-time employees. You want to combine this data to create a comprehensive employee dataset for HR analysis.

Input:

full_time_employees = np.array([ [101, 'John Doe', 'Full-Time', 55000], [102, 'Jane Smith', 'Full-Time', 60000], [103, 'Mike Johnson', 'Full-Time', 52000] ])

part_time_employees = np.array([ [201, 'Alice Brown', 'Part-Time', 25000], [202, 'Bob Wilson', 'Part-Time', 28000], [203, 'Emily Davis', 'Part-Time', 22000] ])

Output:

Combined Employee Data:

Employee ID: 101, Name: John Doe , Type: Full-Time, Salary:55000

Employee ID: 102, Name: Jane Smith , Type: Full-Time, Salary:60000

Employee ID: 103, Name: Mike Johnson , Type: Full-Time, Salary:52000

Employee ID: 201, Name: Alice Brown , Type: Part-Time, Salary:25000

Employee ID: 202, Name: Bob Wilson , Type: Part-Time, Salary:28000

Employee ID: 203, Name: Emily Davis , Type: Part-Time, Salary:22000

In [ ]:
import numpy as np
# Employee data for full-time employees
full_time_employees = np.array([
    [101, 'John Doe', 'Full-Time', 55000],
    [102, 'Jane Smith', 'Full-Time', 60000],
    [103, 'Mike Johnson', 'Full-Time', 52000]
], dtype=object)
# Employee data for part-time employees
part_time_employees = np.array([
    [201, 'Alice Brown', 'Part-Time', 25000],
    [202, 'Bob Wilson', 'Part-Time', 28000],
    [203, 'Emily Davis', 'Part-Time', 22000]
], dtype=object)
# Combine the datasets
combined_employees = np.vstack((full_time_employees, part_time_employees))

print("Combined Employee Data:")
for employee in combined_employees:
    emp_id, name, emp_type, salary = employee
    print("Employee ID: ",emp_id,", Name: ",name,", Type: ",emp_type,", Salary: ",salary)

Combined Employee Data:
Employee ID:  101 , Name:  John Doe , Type:  Full-Time , Salary:  55000
Employee ID:  102 , Name:  Jane Smith , Type:  Full-Time , Salary:  60000
Employee ID:  103 , Name:  Mike Johnson , Type:  Full-Time , Salary:  52000
Employee ID:  201 , Name:  Alice Brown , Type:  Part-Time , Salary:  25000
Employee ID:  202 , Name:  Bob Wilson , Type:  Part-Time , Salary:  28000
Employee ID:  203 , Name:  Emily Davis , Type:  Part-Time , Salary:  22000


#Assignment

Ques: 1 How to find the mean of every NumPy array in the given list?

Input:

list = [ np.array([3, 2, 8, 9]), np.array([4, 12, 34, 25, 78]), np.array([23, 12, 67]) ]

Output:

Mean of each array [5.5,30.6,34.0]

In [ ]:
import numpy as np
list = [
    np.array([3, 2, 8, 9]),
    np.array([4, 12, 34, 25, 78]),
    np.array([23, 12, 67])
]
means=[]
for arr in list:
  mean=np.mean(arr)
  means.append(mean)
print("Mean of Each array: \n",means)

Mean of Each array: 
 [5.5, 30.6, 34.0]


Ques:2 Compute the median of the flattened NumPy array

Input: x_odd = np.array([1, 2, 3, 4, 5, 6, 7])

Output:

Printing the original array:

[1 2 3 4 5 6 7]

Median of the array that contains odd no of elements: 4.0

In [ ]:
import numpy as np
x_odd = np.array([1, 2, 3, 4, 5, 6, 7])

print("Printing the original array:")
print(x_odd)

median_value = np.median(x_odd)
print("\nMedian of the array that contains odd no of elements:\n", median_value)


Printing the original array:
[1 2 3 4 5 6 7]

Median of the array that contains odd no of elements:
 4.0


Ques:3 Compute the standard deviation of the NumPy array

Input: arr = [20, 2, 7, 1, 34]

Output:

arr:[20,2,7,1,34] std of arr : 12.576167933901206

more precision with float32 std of arr : 12.576168

More accuracy with float64 std of arr : 12.576167933901206

In [ ]:
import numpy as np
arr = np.array([20, 2, 7, 1, 34])
print("arr:", arr)

std_default = np.std(arr)
print("\nstd of arr: ", std_default)

arr_float32 = arr.astype(np.float32)
std_float32 = np.std(arr_float32)
print("\nMore precision with float32")
print("std of arr:", std_float32)

arr_float64 = arr.astype(np.float64)
std_float64 = np.std(arr_float64)
print("\nMore precision with float64")
print("std of arr:", std_float64)

arr: [20  2  7  1 34]

std of arr:  12.576167937809991

More precision with float32
std of arr: 12.576168

More precision with float64
std of arr: 12.576167937809991
