#**LAB : 3**

Ques 1: Calculate the total revenue generated by two product categories in a store.

Input:

category1_revenue=np.array([500,600,700,550])

category2_revenue=np.array([450,700,800,600])

Output:

Total Revenue: [950 1300 1500 1150]

In [ ]:
import numpy as np
category1_revenue=np.array([500,600,700,550])
print(" Revenue of product category 1 : \n",category1_revenue)
category2_revenue=np.array([450,700,800,600])
print(" Revenue of product category 2 : \n ",category2_revenue)
tot_revenue=category1_revenue+category2_revenue
print("Total revenue generated by two product: \n",tot_revenue)

 Revenue of product category 1 : 
 [500 600 700 550]
 Revenue of product category 2 : 
  [450 700 800 600]
Total revenue generated by two product: 
 [ 950 1300 1500 1150]


Ques 2: Calculate the profit made by a company

Input:

revenue=np.array([10000, 12000, 11000, 10500])

expenses=np.array([4000,5000,4500,4800])

Output:

Profit:[6000 7000 6500 5700]

In [ ]:
import numpy as np
revenue=np.array([10000, 12000, 11000, 10500])
print("Revenue of a company is :\n",revenue)
expenses=np.array([4000,5000,4500,4800])
print("Expenses of a company is :\n",expenses)
profit=revenue-expenses
print("Profit is :\n",profit)

Revenue of a company is :
 [10000 12000 11000 10500]
Expenses of a company is :
 [4000 5000 4500 4800]
Profit is :
 [6000 7000 6500 5700]


Ques 3: determine which product in a store are out of stock (quantity is 0).

Input: inventory=np.array([10,0,5,0,20,0])

Output: Out of Stock Products: [0 0 0]

In [ ]:
import numpy as np
inventory=np.array([10,0,5,0,20,0])
print("Product in Inventory: \n",inventory)
out_of_stock=inventory[inventory==0]
print("Out of Stock Products: \n",out_of_stock)

Product in Inventory: 
 [10  0  5  0 20  0]
Out of Stock Products: 
 [0 0 0]


Ques 4: Calculate the total cost of items in a shopping cart, considering the quantity and price per item.

Input:

 quantity=np.array([2,3,4,1])

 price_per_item=np.array([10.0,5.0,8.0,12.0])

Output:

Total Cost of Items: [20. 15. 32. 12.]

In [ ]:
import numpy as np
quantity=np.array([2,3,4,1])
print("Quantity of each item in a shpping cart:\n",quantity)
price_per_item=np.array([10.0,5.0,8.0,12.0])
print("Price of each item in a cart: \n",price_per_item)
cost=quantity*price_per_item
print("Total Cost of Items: \n",cost)

Quantity of each item in a shpping cart:
 [2 3 4 1]
Price of each item in a cart: 
 [10.  5.  8. 12.]
Total Cost of Items: 
 [20. 15. 32. 12.]
