#**LAB : 1**

Ques 1: Convert the below list into numpy array then display the array.

Input: my_list=[1,2,3,4,5]

Output: Numpy array: [1 2 3 4 5]

In [2]:
import numpy as np
my_list=[1,2,3,4,5]
print("Input List is: ",my_list)
arr=np.array(my_list)
print("Conversion of the Input List int an Array: ",arr)

Input List is:  [1, 2, 3, 4, 5]
Conversion of the Input List int an Array:  [1 2 3 4 5]


Ques 2: Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and display the result.

Input: my_list=[1,2,3,4,5]

Output:First element:1

Last element: 5

Array after doubling each element: [2 4 6 8 10]

In [1]:
import numpy as np
my_list=[1,2,3,4,5]
print("Input List is: ",my_list)
arr=np.array(my_list)
print("Conversion of the Input List int an Array: ",arr)
first_ele=arr[0]
print("First element: ",first_ele)
last_ele=arr[-1]
print("last element: ",last_ele)
print("Array after doubling each element : ",arr*2)

Input List is:  [1, 2, 3, 4, 5]
Conversion of the Input List int an Array:  [1 2 3 4 5]
First element:  1
last element:  5
Array after doubling each element :  [ 2  4  6  8 10]


Ques 3: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

Sample Output: An array of 10 zeros:

[0.0.0.0.0.0.0.0.0.0.]

An array of 10 ones: [1.1.1.1.1.1.1.1.1.1.]

An array of 10 fives: [5.5.5.5.5.5.5.5.5.5.]

In [3]:
import numpy as np
print("Array of 10 zeros: \n",np.zeros(10))
print("Array of 10 ones: \n",np.ones(10))
print("An array of 10 fives:\n",np.full(10, 5, dtype=float))

Array of 10 zeros: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Ques 4: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Sample Output:

[[2 3 4]

[5 6 7]

[8 9 10]]

In [4]:
import numpy as np
mat=np.arange(2,11).reshape(3,3)
print("3x3 matrix with values ranging from 2 to 10: \n",mat)

3x3 matrix with values ranging from 2 to 10: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
